name: Build OverlayDetect GUI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Compile GUI app
        run: g++ overlay_gui.cpp -o overlay_gui.exe -lpsapi -lgdi32 -static

      - name: Upload .exe
        uses: actions/upload-artifact@c84a6fb479e1b8d8f22560d3a6a113a16c7b9b47
        with:
          name: OverlayDetectGUI
          path: ./overlay_gui.exe
