name: Artifact Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Create test file
        run: echo "Hello from GitHub Actions!" > test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: TestArtifact
          path: test.txt
